[package]
name = "secret-keeper-prompt"
description = "Prompt SecretKeeper, an add-on for https://crates.io/crates/secret-keeper"
version = "0.3.0"
authors = ["stevelr <git@somecool.net>"]
edition = "2018"

[dependencies]
secret-keeper = { path="../../core" }
async-trait = "0.1"
bytes = "0.5"
rpassword = { version = "4.0" }
