# Generator for bash init script run by ci docker image

# Add bash commands and environment settings
#   after the second 'cat' (after about line 10) and before 'EBASH'
# Environment variables (for example, $KEY) are expanded on the host.
#   (host vars may be added to ./secret.env)
# Variable escaped with '\' (for example, \$HOME) are expanded on the ci container.
cat >>$1 <<_EOF
# add variable settings to bashrc so they work in ci steps later in the pipeline
cat >>"\$BASH_ENV" <<_EBASH
# local config - this file is automatically generated
# add environment settings below this line and before EBASH
export GOOGLE_APPLICATION_CREDENTIALS="\$HOME/gcloud-service-key.json"
export GOOGLE_COMPUTE_ZONE="$GOOGLE_COMPUTE_ZONE"
export CLOUDKMS_KEYRING_NAME="$CLOUDKMS_KEYRING_NAME"
export CLOUDKMS_KEY_NAME="$CLOUDKMS_KEY_NAME"
_EBASH
_EOF

