# Template for environment file that is run by ci docker image

# Environment variables referenced here are expanded on the host
# if you escape with \$, it is expanded on the ci container.
cat >$1 <<_EOF
# add files to bashrc so they work in future steps
cat >>"\$BASH_ENV" <<_EBASH
# local config - this file is automatically generated
# add environment settings below
export GOOGLE_APPLICATION_CREDENTIALS="\$HOME/gcloud-service-key.json"
#export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"
export GOOGLE_PROJECT_ID="$GOOGLE_PROJECT_ID"
export GOOGLE_COMPUTE_ZONE="$GOOGLE_COMPURE_ZONE"
export CLOUDKMS_KEYRING_NAME="$CLOUDKMS_KEYRING_NAME"
export CLOUDKMS_KEY_NAME="$CLOUDKMS_KEY_NAME"
_EBASH
_EOF

