#!/bin/sh

# Run drone pipeline locally
#
# args:
#   (none)                  run default pipeline
#   --pipeline full         run including hashivault and encrypt-rs tests
#   --pipeline nightly-full run including hashivault and encrypt-rs tests
#

if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
	echo Define GOOGLE_APPLICATION_CREDENTIALS first
	exit 1
fi

mkdir -p -m 0700 /tmp/.secret-keeper/
cp $GOOGLE_APPLICATION_CREDENTIALS /tmp/.secret-keeper/credentials.json

if [ -z "$1" ]; then
	drone exec --trusted --pipeline default
else
	drone exec --trusted "$@"
fi
